# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# python virtualenvwrapper settings
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=~/.virtualenvs/
. /usr/local/bin/virtualenvwrapper.sh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew brew-cask cp django docker fabric git github history knife meteor mvn node npm nvm rake rails rake redis-cli rsync ruby rvm svn tmux vagrant)
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export DYLD_LIBRARY_PATH="/usr/local/oracle/instantclient_11_2"
#export PATH=$PATH:$DYLD_LIBRARY_PATH
sudo () { ( unset LD_LIBRARY_PATH DYLD_LIBRARY_PATH; exec command sudo $* ) }
export ORACLE_HOME=$HOME"/instantclient_11_2"
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export PATH=$PATH:$DYLD_LIBRARY_PATH
export SQLPATH=$HOME"/instantclient_11_2"
export TNS_ADMIN=$HOME"/Documents"
export NLS_LANG="AMERICAN_AMERICA.UTF8"
alias sqlplus='rlwrap sqlplus'

#export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export MAVEN_OPTS=-Xmx512M

#nvm
source /usr/local/opt/nvm/nvm.sh
export NODE_PATH=/usr/local/share/npm/lib/node_modules

#ruby
#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#VIM
export EDITOR=/usr/local/bin/vim

#tomcat
export TOMCAT_HOME=/usr/local/Cellar/tomcat7/7.0.59/libexec/webapps
export UNIFIED_CONTENT=/usr/local/Cellar/tomcat7/7.0.59/libexec/webapps/discern/static_content/UnifiedContent

#haskell
export PATH=$PATH:$HOME/.cabal/bin
