# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=7

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# python virtualenvwrapper settings
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache
export PIP_REQUIRE_VIRTUALENV=true
export WORKON_HOME=~/.virtualenvs/
. /usr/local/bin/virtualenvwrapper.sh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew brew-cask cp django docker fabric git github grunt history knife meteor mvn node npm nvm rake rails rake redis-cli rsync ruby rvm svn tmux vagrant)
source $ZSH/oh-my-zsh.sh

# Customize to your needs...
sudo () { ( unset LD_LIBRARY_PATH DYLD_LIBRARY_PATH; exec command sudo $* ) }

export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export MAVEN_OPTS=-Xmx512M

#nvm
source /usr/local/opt/nvm/nvm.sh
export NODE_PATH=/usr/local/share/npm/lib/node_modules

#VIM
export EDITOR=/usr/local/bin/vim

#haskell
PATH=$PATH:$HOME/.cabal/bin

#go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

#ruby
export PATH=$PATH:$HOME/.rvm/bin

export C2FO_HOME=/Users/richard.moorhead/git/c2fo

export NODE_ENV=dockerdev

