ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=7

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# python virtualenvwrapper settings
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
#export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache
#export PIP_REQUIRE_VIRTUALENV=true
#export WORKON_HOME=~/.virtualenvs/
#. /usr/local/bin/virtualenvwrapper.sh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew brew-cask cp django docker fabric git github grunt history knife meteor mvn node npm nvm rake rails rake redis-cli rsync ruby rvm svn tmux vagrant)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
sudo () { ( unset LD_LIBRARY_PATH DYLD_LIBRARY_PATH; exec command sudo $* ) }

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
export MAVEN_OPTS=-Xmx512M

#nvm
source /usr/local/opt/nvm/nvm.sh
export NODE_PATH=/usr/local/share/npm/lib/node_modules

#vim
export EDITOR=/usr/local/bin/vim

#haskell
PATH=$PATH:$HOME/.cabal/bin

#go
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

#ruby
export PATH=$PATH:$HOME/.rvm/bin

#anaconda
export PATH=$HOME/anaconda2/bin:$PATH
export DYLD_FALLBACK_LIBRARY_PATH=$HOME/anaconda2/lib/:$DYLD_FALLBACK_LIBRARY_PATH

export C2FO_HOME=/Users/richard.moorhead/git/c2fo
export C2FO_GO=/Users/richard.moorhead/go/src/github.com/c2fo/c2fo-go/

export NODE_ENV=dockerdev
export SPARK_ENV=dockerdev

#docker
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=/Users/richard.moorhead/.docker/machine/machines/default
export DOCKER_TLS_VERIFY=1

#spark
export SPARK_HOME=/usr/local/Cellar/apache-spark/1.6.0/libexec
export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH
export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH
export PYSPARK_PYTHON=/usr/local/bin/bpython

#sbt
JAVA_OPTS='-Xmx4g -Xms512M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m'

#aws
source /usr/local/share/zsh/site-functions/_aws

#ATLAS
source /Users/richard.moorhead/.atlasrc

#Android
ANDROID_HOME=/Users/richard.moorhead/Library/Android/sdk
PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
